repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # frozen: v4.5.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0  # frozen: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
